# Generated by Django 2.0.3 on 2018-03-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('mobile', models.CharField(max_length=20, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('address', models.CharField(max_length=250, verbose_name='Address')),
                ('designation', models.CharField(max_length=250, verbose_name='Designation')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=250, verbose_name='School')),
                ('degree', models.CharField(max_length=250, verbose_name='Degree')),
                ('obtain_gpa', models.FloatField(verbose_name='Obtain GPA')),
                ('total_gpa', models.FloatField(verbose_name='Total GPA')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250, verbose_name='Designation')),
                ('company', models.CharField(max_length=250, verbose_name='Company')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('level', models.IntegerField(verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('linkedin', models.CharField(max_length=100, verbose_name='LinkedIn')),
                ('google_plus', models.CharField(max_length=100, verbose_name='GooglePlus')),
                ('github', models.CharField(max_length=100, verbose_name='Github')),
                ('youtube', models.CharField(max_length=100, verbose_name='Youtube')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.SkillCategory'),
        ),
    ]
