# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20180321_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('bg-warning', 'Warning'), ('bg-info', 'Info'), ('bg-primary', 'Primary'), ('bg-danger', 'Danger'), ('bg-success', 'Success')], default='bg-success', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
