# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20180324_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='skill',
            name='color',
            field=models.CharField(choices=[('bg-danger', 'Danger'), ('bg-primary', 'Primary'), ('bg-warning', 'Warning'), ('bg-success', 'Success'), ('bg-info', 'Info')], default='bg-success', max_length=50, verbose_name='Color'),
        ),
    ]
